import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 사이드바는 docs/ 폴더 구조 + 각 문서의 frontmatter(sidebar_position)로 자동 생성한다.
// 새 문서를 추가하면 별도 수정 없이 자동 반영됨.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
